### ISSUE TITLE
Would it make sense to rename the `set` expression type to something like `expr`?

### ISSUE THREAD

**Issue by XedinUnknown** [RebelCode/rcmod-wp-cqrs#7]
The current type "set" is an uncommon acronym. Also, it is a word in English. These factors are quite confusing.

**Comment by mecha** [comment]
But it's not an acronym. It actually represents what the English word means. A set.

For reference, I mentioned this [here](https://github.com/RebelCode/rcmod-eddbk-booking-logic/pull/20#discussion_r202728566) yesterday as well.

**Comment by XedinUnknown** [comment]
All clear now, thank you.
